networks:
  proxy:
    name: proxy

services:

  proxy:
    image: traefik:v3.1
    container_name: akka-proxy
    restart: always
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/config
      - --providers.file.watch=true
      - --serversTransport.insecureSkipVerify=true

    labels:
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-to-https@docker
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https

    ports:
      - 80:80
      - 443:443
      - 9876:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/config/
      - .user/cert:/cert/
    networks:
      - proxy

  pma:
    container_name: akka-pma
    image: phpmyadmin
    profiles:
      - utils
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      PMA_ABSOLUTE_URI: https://pma.akka.test
      PMA_HOSTS: fof-db,extrakt-db,ca-db,installatorsforetagen-db,ng-db
    networks:
      - proxy
    labels:
      - traefik.http.routers.akka-pma.rule=Host(`pma.akka.test`)
      - traefik.http.routers.akka-pma.tls=true
      - traefik.http.routers.akka-pma.entrypoints=web,websecure



